### ISSUE TITLE
Doesn't work with vs2019 (Version 16.11.2) ?

### ISSUE THREAD

**Issue by andygemis** [microsoft/CsWin32#896]
## Actual behavior

Under vs 2022 - have a sln/csproj and the source generator is working correctly.

Open same sln with 2019 - then get following error

1>CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

![image](https://user-images.githubusercontent.com/48239545/226922495-836151cb-4466-4efa-911a-e62658239123.png)

## Repro steps

1. `NativeMethods.txt` content:
```
SCardEstablishContext
SCardReleaseContext
SCardListReaderGroups
SCardListReaders
SCardGetStatusChange
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "emitSingleFile": true,
  "public": true
}
```

### Context

- CsWin32 version: 0.2.206-beta
- Target Framework: .net framework 4.8
